name: traceablespeech  # Change this to your preferred environment name
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip
  - pip:
      - absl-py==1.4.0
      - altair==5.1.2
      - appdirs==1.4.4
      - astunparse==1.6.3
      - attrs==23.1.0
      - audioread==3.0.0
      - augly==1.0.0
      - backports.zoneinfo==0.2.1
      - blinker==1.6.3
      - brotlipy==0.7.0
      - cachetools==5.3.1
      - certifi
      - cffi
      - charset-normalizer
      - click==8.1.7
      - contourpy==1.1.0
      - cryptography
      - cycler==0.11.0
      - decorator==5.1.1
      - einops==0.6.1
      - filelock==3.13.1
      - flatbuffers==23.5.26
      - fonttools==4.42.0
      - fsspec==2023.12.2
      - gast==0.4.0
      - gitdb==4.0.11
      - GitPython==3.1.40
      - google-auth==2.22.0
      - google-auth-oauthlib==0.4.6
      - google-pasta==0.2.0
      - grpcio==1.56.2
      - h5py==3.9.0
      - huggingface-hub==0.20.3
      - idna
      - imageio==2.31.1
      - importlib-metadata==6.8.0
      - importlib-resources==6.0.0
      - iopath==0.1.10
      - Jinja2==3.1.2
      - joblib==1.3.1
      - jsonpatch==1.33
      - jsonpointer==2.4
      - jsonschema==4.19.1
      - jsonschema-specifications==2023.7.1
      - keras==2.10.0
      - Keras-Preprocessing==1.1.2
      - kiwisolver==1.4.4
      - lazy_loader==0.3
      - libclang==16.0.6
      - librosa==0.9.2
      - lightning-utilities==0.9.0
      - llvmlite==0.40.1
      - Markdown==3.4.4
      - markdown-it-py==3.0.0
      - MarkupSafe==2.1.3
      - matplotlib==3.7.1
      - mdurl==0.1.2
      - mkl-fft==1.3.6
      - mkl-random
      - mkl-service==2.4.0
      - msgpack==1.0.5
      - networkx==3.1
      - numba==0.57.1
      - numpy
      - oauthlib==3.2.2
      - opt-einsum==3.3.0
      - packaging==23.1
      - pandas==1.4.4
      - pesq==0.0.4
      - Pillow==9.4.0
      - pkgutil_resolve_name==1.3.10
      - pooch==1.6.0
      - portalocker==2.8.2
      - protobuf==3.20.1
      - pyarrow==13.0.0
      - pyasn1==0.5.0
      - pyasn1-modules==0.3.0
      - pycparser
      - pydeck==0.8.1b0
      - pydub==0.25.1
      - Pygments==2.16.1
      - pyOpenSSL
      - pyparsing==3.1.1
      - PySocks
      - pystoi==0.3.3
      - python-dateutil==2.8.2
      - python-magic==0.4.27
      - pytz==2023.3
      - pyvad==0.2.0
      - PyWavelets==1.4.1
      - PyYAML==6.0.1
      - referencing==0.30.2
      - regex==2023.8.8
      - requests
      - requests-oauthlib==1.3.1
      - resampy==0.4.2
      - rich==13.6.0
      - rpds-py==0.10.6
      - rsa==4.9
      - scikit-image==0.19.3
      - scikit-learn==1.3.0
      - scipy==1.10.1
      - seaborn==0.11.2
      - shortuuid==1.0.11
      - six==1.16.0
      - smmap==5.0.1
      - soundfile==0.12.1
      - soxr==0.3.5
      - speechpy==2.4
      - streamlit==1.27.2
      - tenacity==8.2.3
      - tensorboard==2.10.1
      - tensorboard-data-server==0.6.1
      - tensorboard-plugin-wit==1.8.1
      - tensorflow-estimator==2.10.0
      - tensorflow-gpu==2.10.0
      - tensorflow-io-gcs-filesystem==0.33.0
      - termcolor==2.3.0
      - threadpoolctl==3.2.0
      - tifffile==2023.7.10
      - toml==0.10.2
      - toolz==0.12.0
      - torch==1.13.0
      - torchaudio==0.13.0
      - torchmetrics==1.0.3
      - torchnet==0.0.4
      - torchvision==0.14.0
      - tornado==6.3.3
      - tqdm==4.65.0
      - typing_extensions
      - tzlocal==5.1
      - urllib3
      - validators==0.22.0
      - visdom==0.2.4
      - watchdog==3.0.0
      - wavmark==0.0.3
      - webrtcvad==2.0.10
      - websocket-client==1.8.0
      - Werkzeug==2.3.6
      - wrapt==1.15.0
      - youtube-dl==2021.12.17
      - zipp==3.16.2
